services:
  shopping-service:
    container_name: shopping-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SSV_SERVER_BIND_ADDR:-0.0.0.0:3009}:3009"
    environment:
      - SSV_ENVIRONMENT=${SSV_ENVIRONMENT:-production}
      - SSV_SERVER_BIND_ADDR=0.0.0.0:3009
      - SSV_SERVER_READ_TIMEOUT=${SSV_SERVER_READ_TIMEOUT:-60}
      - SSV_LOG_FORMAT=${SSV_LOG_FORMAT:-json}
      - SSV_LOG_LEVEL=${SSV_LOG_LEVEL:-info}
      - SSV_RATE_LIMIT_MAX=${SSV_RATE_LIMIT_MAX:-1000}
      - SSV_RATE_LIMIT_WINDOW=${SSV_RATE_LIMIT_WINDOW:-60}
      - SSV_DB_HOST=${SSV_DB_HOST}
      - SSV_DB_PORT=${SSV_DB_PORT}
      - SSV_DB_SSL=${SSV_DB_SSL:-disable}
      - SSV_DB_USER=${SSV_DB_USER}
      - SSV_DB_PASSWORD=${SSV_DB_PASSWORD}
      - SSV_DB_DATABASE=${SSV_DB_DATABASE}
      - SSV_DB_MAX_CONNECTIONS=${SSV_DB_MAX_CONNECTIONS:-100}
      - SSV_REDIS_HOST=${SSV_REDIS_HOST}
      - SSV_REDIS_PORT=${SSV_REDIS_PORT}
      - SSV_REDIS_DB=${SSV_REDIS_DB:-0}
      - SSV_REDIS_USER=${SSV_REDIS_USER}
      - SSV_REDIS_PASS=${SSV_REDIS_PASS}
      - SSV_OTLP_ENDPOINT=${SSV_OTLP_ENDPOINT:-otel-collector:4317}
      - SSV_JAEGER_ENDPOINT=${SSV_JAEGER_ENDPOINT}
      - SSV_TELEGRAM_BOT_TOKEN=${SSV_TELEGRAM_BOT_TOKEN}
      - SSV_TELEGRAM_DEBUG=${SSV_TELEGRAM_DEBUG:-false}
      - SSV_TELEGRAM_ADMINS=${SSV_TELEGRAM_ADMINS}
      - SSV_OPENAI_API_KEY=${SSV_OPENAI_API_KEY}
      - SSV_OPENAI_MODEL=${SSV_OPENAI_MODEL}
      - SSV_OPENAI_BASE_URL=${SSV_OPENAI_BASE_URL}
      - SSV_OPENAI_MAX_TOKENS=${SSV_OPENAI_MAX_TOKENS}
      - SSV_OPENAI_TEMPERATURE=${SSV_OPENAI_TEMPERATURE}
      - SSV_AZURE_SPEECH_KEY=${SSV_AZURE_SPEECH_KEY}
      - SSV_AZURE_SPEECH_REGION=${SSV_AZURE_SPEECH_REGION}
      - SSV_CLOUD_PROVIDER=${SSV_CLOUD_PROVIDER}
      - SSV_AZURE_STORAGE_CONNECTION_STRING=${SSV_AZURE_STORAGE_CONNECTION_STRING}
      - SSV_AZURE_STORAGE_CONTAINER_NAME=${SSV_AZURE_STORAGE_CONTAINER_NAME}
      - SSV_AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT=${SSV_AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT}
      - SSV_AZURE_DOCUMENT_INTELLIGENCE_API_KEY=${SSV_AZURE_DOCUMENT_INTELLIGENCE_API_KEY}
      - SSV_AZURE_DOCUMENT_INTELLIGENCE_API_VERSION=${SSV_AZURE_DOCUMENT_INTELLIGENCE_API_VERSION}
      - SSV_AZURE_DOCUMENT_INTELLIGENCE_RECEIPT_MODEL=${SSV_AZURE_DOCUMENT_INTELLIGENCE_RECEIPT_MODEL}
    restart: unless-stopped
    networks:
      - shopping-network
      - observability_observability
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shopping-network:
    external: true
  observability_observability:
    external: true