name: Deploy Shopping Service

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}

    - name: Add Hetzner server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.HETZNER_SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -o ConnectTimeout=10 root@${{ secrets.HETZNER_SERVER_IP }} "echo 'SSH connection successful'"

    - name: Install dependencies on server
      run: |
        ssh root@${{ secrets.HETZNER_SERVER_IP }} << 'EOF'
          if ! command -v go &> /dev/null; then
            wget https://go.dev/dl/go1.25.1.linux-amd64.tar.gz
            tar -C /usr/local -xzf go1.25.1.linux-amd64.tar.gz
            echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
          fi
          echo "Dependencies ready"
        EOF

    - name: Create deployment directory and copy files
      run: |
        ssh root@${{ secrets.HETZNER_SERVER_IP }} "mkdir -p /opt/shopping-service"
        scp -r * root@${{ secrets.HETZNER_SERVER_IP }}:/opt/shopping-service/

    - name: Create production environment file
      run: |
        ssh root@${{ secrets.HETZNER_SERVER_IP }} << 'EOF'
          cd /opt/shopping-service
          cat > .env << 'ENV_EOF'
          SSV_ENVIRONMENT=${{ vars.SSV_ENVIRONMENT }}
          SSV_SERVER_BIND_ADDR=${{ vars.SSV_SERVER_BIND_ADDR }}
          SSV_SERVER_READ_TIMEOUT=${{ vars.SSV_SERVER_READ_TIMEOUT }}
          SSV_LOG_FORMAT=${{ vars.SSV_LOG_FORMAT }}
          SSV_LOG_LEVEL=${{ vars.SSV_LOG_LEVEL }}
          SSV_RATE_LIMIT_MAX=${{ vars.SSV_RATE_LIMIT_MAX }}
          SSV_RATE_LIMIT_WINDOW=${{ vars.SSV_RATE_LIMIT_WINDOW }}
          SSV_DB_HOST=${{ vars.SSV_DB_HOST }}
          SSV_DB_PORT=${{ vars.SSV_DB_PORT }}
          SSV_DB_SSL=${{ vars.SSV_DB_SSL }}
          SSV_DB_USER=${{ vars.SSV_DB_USER }}
          SSV_DB_PASSWORD=${{ secrets.SSV_DB_PASSWORD }}
          SSV_DB_DATABASE=${{ vars.SSV_DB_DATABASE }}
          SSV_DB_MAX_CONNECTIONS=${{ vars.SSV_DB_MAX_CONNECTIONS }}
          SSV_REDIS_HOST=${{ vars.SSV_REDIS_HOST }}
          SSV_REDIS_PORT=${{ vars.SSV_REDIS_PORT }}
          SSV_REDIS_DB=${{ vars.SSV_REDIS_DB }}
          SSV_REDIS_USER=${{ vars.SSV_REDIS_USER }}
          SSV_REDIS_PASS=${{ secrets.SSV_REDIS_PASS }}
          SSV_OTLP_ENDPOINT=${{ vars.SSV_OTLP_ENDPOINT }}
          SSV_JAEGER_ENDPOINT=${{ vars.SSV_JAEGER_ENDPOINT }}
          SSV_TELEGRAM_BOT_TOKEN=${{ secrets.SSV_TELEGRAM_BOT_TOKEN }}
          SSV_TELEGRAM_DEBUG=${{ vars.SSV_TELEGRAM_DEBUG }}
          SSV_TELEGRAM_ADMINS=${{ secrets.SSV_TELEGRAM_ADMINS }}
          SSV_OPENAI_API_KEY=${{ secrets.SSV_OPENAI_API_KEY }}
          SSV_OPENAI_MODEL=${{ vars.SSV_OPENAI_MODEL }}
          SSV_OPENAI_BASE_URL=${{ vars.SSV_OPENAI_BASE_URL }}
          SSV_OPENAI_MAX_TOKENS=${{ vars.SSV_OPENAI_MAX_TOKENS }}
          SSV_OPENAI_TEMPERATURE=${{ vars.SSV_OPENAI_TEMPERATURE }}
          SSV_AZURE_SPEECH_KEY=${{ secrets.SSV_AZURE_SPEECH_KEY }}
          SSV_AZURE_SPEECH_REGION=${{ vars.SSV_AZURE_SPEECH_REGION }}
          SSV_CLOUD_PROVIDER=${{ vars.SSV_CLOUD_PROVIDER }}
          SSV_AZURE_STORAGE_CONNECTION_STRING=${{ secrets.SSV_AZURE_STORAGE_CONNECTION_STRING }}
          SSV_AZURE_STORAGE_CONTAINER_NAME=${{ vars.SSV_AZURE_STORAGE_CONTAINER_NAME }}
          SSV_AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT=${{ secrets.SSV_AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT }}
          SSV_AZURE_DOCUMENT_INTELLIGENCE_API_KEY=${{ secrets.SSV_AZURE_DOCUMENT_INTELLIGENCE_API_KEY }}
          SSV_AZURE_DOCUMENT_INTELLIGENCE_API_VERSION=${{ vars.SSV_AZURE_DOCUMENT_INTELLIGENCE_API_VERSION }}
          SSV_AZURE_DOCUMENT_INTELLIGENCE_RECEIPT_MODEL=${{ vars.SSV_AZURE_DOCUMENT_INTELLIGENCE_RECEIPT_MODEL }}
          ENV_EOF
        EOF

    - name: Deploy shopping service
      run: |
        ssh root@${{ secrets.HETZNER_SERVER_IP }} << 'EOF'
          cd /opt/shopping-service
          export PATH=$PATH:/usr/local/go/bin
          systemctl stop shopping-service || true
          docker compose -f docker-compose.prod.yml down || true
          docker compose -f docker-compose.prod.yml up -d
          echo "Waiting for database to be ready..."
          sleep 15
          echo "Building shopping service..."
          go mod tidy
          go build -o shopping-service cmd/main.go
          cat > /etc/systemd/system/shopping-service.service << 'SERVICE_EOF'
          [Unit]
          Description=Shopping Service
          After=network.target docker.service
          Wants=docker.service

          [Service]
          Type=simple
          User=root
          WorkingDirectory=/opt/shopping-service
          ExecStart=/opt/shopping-service/shopping-service
          Restart=always
          RestartSec=5
          EnvironmentFile=/opt/shopping-service/.env

          [Install]
          WantedBy=multi-user.target
          SERVICE_EOF
          systemctl daemon-reload
          systemctl enable shopping-service
          systemctl restart shopping-service
          echo "Deployment completed!"
        EOF

    - name: Verify deployment
      run: |
        ssh root@${{ secrets.HETZNER_SERVER_IP }} << 'EOF'
          echo "=== Service Status ==="
          systemctl status shopping-service --no-pager
          echo ""
          echo "=== Health Check ==="
          sleep 10
          curl -f http://localhost:3009/health || echo "Health check failed (service may still be starting)"
          echo ""
          echo "=== Service Logs (last 20 lines) ==="
          journalctl -u shopping-service --no-pager -n 20
          echo ""
          echo "=== Port Check ==="
          netstat -tlnp | grep :3009 || echo "Service not listening on port 3009"
          echo ""
          echo "=== Process Check ==="
          ps aux | grep shopping-service | grep -v grep || echo "Shopping service process not found"
        EOF

    - name: Create deployment summary
      run: |
        cat << 'EOF' >> $GITHUB_STEP_SUMMARY
        ## 🚀 Shopping Service Deployment

        **Environment**: ${{ github.event.inputs.environment || 'production' }}
        **Server**: ${{ secrets.HETZNER_SERVER_IP }}
        **Commit**: ${{ github.sha }}

        ### 🔧 Service Details:
        - **API Endpoint**: http://${{ secrets.HETZNER_SERVER_IP }}:3009
        - **Health Check**: http://${{ secrets.HETZNER_SERVER_IP }}:3009/health
        - **Environment**: Production
        - **OTLP Endpoint**: Connected to observability stack
        - **Database**: PostgreSQL via Docker Compose

        ### 📊 Monitoring:
        - **Logs**: Available in Grafana/Loki
        - **Metrics**: Available in Prometheus/Grafana
        - **Traces**: Available in Jaeger
        - **System Logs**: `journalctl -u shopping-service -f`

        ### 🗃️ Database:
        - **Migrations**: Run separately via Migration workflow
        - **Manual Migration**: Use Migration workflow in Actions tab

        **Deployment Status**: ✅ Complete
        EOF

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Notify deployment result
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "✅ Shopping service deployed successfully to ${{ secrets.HETZNER_SERVER_IP }}:3009"
        else
          echo "❌ Shopping service deployment failed"
        fi